---
# yamllint disable rule:line-length

name: PR and branch sanity
on:  # yamllint disable-line rule:truthy
  push:
    tags:
      - v*
    branches:
      - release-*
      - mainfoo
  pull_request:
    branches:
      - '*'
env:
  GO_VERSION: "1.16"
  # Uses image name IMG to build image in Makefile
  IMG: "quay.io/ramendr/ramen-operator:sanity"
  IMG_NAME: "quay.io/ramendr/ramen-operator"
defaults:
  run:
    shell: bash
jobs:
  publish-image:
    name: Publish built image
    if: >
      (github.event_name == 'push') &&
      (github.ref == 'refs/heads/mainfoo' ||
       startsWith(github.ref, 'refs/heads/release-') ||
       startsWith(github.ref, 'refs/tags/v')) &&
      (github.repository == 'shyamsundarr/ramen')
    runs-on: ubuntu-20.04
    steps:
      - name: Push to Quay
        run: |
          [[ "${{ github.ref }}" =~ ^refs\/(heads|tags)\/(release-)?(.*) ]]
          echo "${BASH_REMATCH[1]}" "${BASH_REMATCH[2]}" "${BASH_REMATCH[3]}"
          TAG=""
          if test "${BASH_REMATCH[1]}" = "heads"; then
            if test "${BASH_REMATCH[2]}" = "" && test "${BASH_REMATCH[3]}" = "mainfoo"; then
              TAG="canary"
            elif test "${BASH_REMATCH[2]}" = "release-"; then
              TAG="${BASH_REMATCH[3]}-canary"
            fi
          elif test "${BASH_REMATCH[1]}" == "tags" && test "${BASH_REMATCH[2]}" = ""; then
            TAG="${BASH_REMATCH[3]}"
          fi
          test "${TAG}" = "" && exit 1
          echo "$TAG"
