---
# yamllint disable rule:line-length

name: PR and branch sanity
on:  # yamllint disable-line rule:truthy
  push:
    tags:
      - v*
    branches:
      - release-*
      - main
  pull_request:
    branches:
      - '*'
env:
  GO_VERSION: "1.16"
  # Use IMAGE_TAG_BASE and IMAGE_TAG Makefile variables to build various images
  IMAGE_TAG_BASE: "quay.io/shyamsundarr/ramen"
  IMAGE_TAG: "sanity"
defaults:
  run:
    shell: bash
jobs:
  build-image-and-ensure-clean-branch:
    name: Build image and ensure clean branch
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build image
        run: make docker-build

      - name: Export image
        run: docker save -o /tmp/ramen-operator.tar ${IMAGE_TAG_BASE}-operator:${IMAGE_TAG}

      - name: Save image artifact
        uses: actions/upload-artifact@v2
        with:
          name: ramen-operator
          path: /tmp/ramen-operator.tar
          retention-days: 1

      - name: Go tidy
        run: go mod tidy

      - name: Git branch sanity
        run: |
          echo "Failing if any auto generated files are updated, checking 'git status'"
          git --no-pager diff
          git status --porcelain 2>&1 | tee /dev/stderr | (! read)

  publish-image:
    name: Publish built image
    needs: [build-image-and-ensure-clean-branch]
    if: >
      (github.event_name == 'push') &&
      (github.ref == 'refs/heads/main' ||
       startsWith(github.ref, 'refs/heads/release-') ||
       startsWith(github.ref, 'refs/tags/v')) &&
      (github.repository == 'shyamsundarr/ramen')
    runs-on: ubuntu-20.04
    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v1
        with:
          name: ramen-operator
          path: /tmp

      - name: Load image artifact
        run: |
          docker load -i /tmp/ramen-operator.tar

      - name: Login to Quay
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Determine image tag
        run: |
          [[ "${{ github.ref }}" =~ ^refs\/(heads|tags)\/(release-)?(.*) ]]
          echo "heads or tags? ${BASH_REMATCH[1]}"
          echo "release? ${BASH_REMATCH[2]}"
          echo "version? ${BASH_REMATCH[3]}"
          TAG=""
          if test "${BASH_REMATCH[1]}" = "heads"; then
            if test "${BASH_REMATCH[2]}" = "" && test "${BASH_REMATCH[3]}" = "main"; then
              TAG="canary"
            elif test "${BASH_REMATCH[2]}" = "release-"; then
              TAG="${BASH_REMATCH[3]}-canary"
            fi
          elif test "${BASH_REMATCH[1]}" == "tags" && test "${BASH_REMATCH[2]}" = ""; then
            TAG="${BASH_REMATCH[3]}"
          fi
          test "${TAG}" = "" && exit 1
          echo "Publish image tag ${TAG}"
          echo "publish_image_tag=${TAG}" >> $GITHUB_ENV

      - name: Push operator image to Quay
        run: |
          docker tag "${IMAGE_TAG_BASE}-operator:${IMAGE_TAG}" "${IMAGE_TAG_BASE}-operator:${{ env.publish_image_tag }}"
          docker push "${IMAGE_TAG_BASE}-operator:${{ env.publish_image_tag }}"

      # TODO: We do not need to build bundles and catalogs each time, fix once we reach alpha
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build and push bundle images to Quay
        run: |
          IMAGE_TAG="${{ env.publish_image_tag }}" make bundle-build bundle-push

      - name: Build and push catalog image to Quay
        run: |
          IMAGE_TAG="${{ env.publish_image_tag }}" make catalog-build catalog-push
